name: Deploy Beta

on:
  push:
    branches:
      - beta

jobs:
  test:
    uses: boilerplate/.github/workflows/pull_request.yml@master
    with:
      REACT_APP_API_URL: https://api.beta.test.net/v1/cms
      REACT_APP_COMMON_API_URL: https://api.beta.test.net/v1
  deploy:
    uses: boilerplate/.github/workflows/deploy.yml@master
    with:
      environment: beta
      environment_url: https://cms.beta.test.net/
      version: ${{ needs.test.outputs.version }}
    secrets:
      GCP_SA_KEY: ${{ secrets.GCP_SA_KEY }}
    needs:
      - test
